name: IaC Security Check

on:
  push:
    branches:
      - test-checkov
  pull_request:
    branches:
      - main

jobs:
  checkov-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install Checkov
        run: pip install checkov

      - name: Run Checkov scan and generate JSON
        run: checkov -d . --output json > checkov_report.json || true

      - name: Convert Checkov JSON to Markdown
        run: python .github/scripts/convert_to_md.py checkov_report.json checkov_report.md || true

      - name: Debug – Show files
        run: ls -la

      - name: Upload Markdown report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: checkov-markdown-report
          path: checkov_report.md
