name: IaC Security Check

on:
  push:
    branches:
      - test-checkov
  pull_request:
    branches:
      - main

jobs:
  checkov_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Checkov
        run: |
          python -m pip install --upgrade pip
          pip install checkov

      - name: Run Checkov scan
  run: |
    checkov -d . --output json -o json > checkov_report.json || true


      - name: Upload Checkov Report
        uses: actions/upload-artifact@v4
        with:
          name: checkov-report
          path: checkov_report.json

      - name: Convert Checkov JSON to Markdown
        run: python .github/scripts/convert_to_md.py

      - name: Upload Markdown Report
        uses: actions/upload-artifact@v4
        with:
          name: markdown-report
          path: checkov_report.md
