name: IaC Security Check

on:
  push:
    branches:
      - test-checkov
  pull_request:
    branches:
      - main

jobs:
  checkov_scan:
    name: Run Checkov and Generate Report
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install checkov

      - name: Run Checkov scan and output JSON
        run: checkov -d . --output json > checkov_report.json || true

      - name: Convert JSON to Markdown Report
        run: python .github/scripts/convert_to_md.py checkov_report.json checkov_report.md || true

      - name: Upload Checkov Reports
        uses: actions/upload-artifact@v4
        with:
          name: checkov-reports
          path: |
            checkov_report.json
            checkov_report.md
