name: IaC Security Check

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - test-checkov

jobs:
  checkov_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install checkov matplotlib

      - name: Run Checkov scan and output JSON
        run: checkov -d . -o json > checkov_report.json || true

      - name: Convert JSON to Markdown
        run: python .github/scripts/convert_to_md.py checkov_report.json checkov_report.md || true

      - name: Generate severity summary chart
        run: python .github/scripts/severity_summary_chart.py checkov_report.json severity_summary_chart.md || true

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: |
            checkov_report.json
            checkov_report.md
            severity_summary_chart.md

      - name: Block PR on Critical Issues
        run: python .github/scripts/block_on_critical.py checkov_report.json

      - name: Upload Fixed Files
        uses: actions/upload-artifact@v4
        with:
          name: fixed-iac-files
          path: '**/*_fixed.tf'


   