name: IaC Security Check

permissions:
  contents: read
  pull-requests: write

on:
  push:
    branches: [main, test-checkov]
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main]

jobs:
  checkov_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Checkov and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install checkov matplotlib

      - name: Run Checkov scan and output JSON
        run: checkov -d . -o json > checkov_report.json || true

      - name: Convert JSON to Markdown
        run: python .github/scripts/convert_to_md.py checkov_report.json checkov_report.md || true

      - name: Generate Severity Summary Chart
        run: python .github/scripts/severity_summary_chart.py checkov_report.json severity_summary_chart.md || true

      - name: Upload Markdown report
        uses: actions/upload-artifact@v4
        with:
          name: checkov-markdown-report-${{ github.run_id }}
          path: checkov_report.md

      - name: Upload JSON report
        uses: actions/upload-artifact@v4
        with:
          name: checkov-json-report-${{ github.run_id }}
          path: checkov_report.json

      - name: Upload Severity Chart report
        uses: actions/upload-artifact@v4
        with:
          name: severity-summary-chart-${{ github.run_id }}
          path: severity_summary_chart.md

      - name: Block PR on Critical Issues
        run: python .github/scripts/block_on_critical.py checkov_report.json

      - name: Post Checkov Report to PR
        if: github.event_name == 'pull_request'
        run: python .github/scripts/post_comment.py checkov_report.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.pull_request.number }}

      - name: Post Severity Chart to PR
        if: github.event_name == 'pull_request'
        run: python .github/scripts/post_comment.py severity_summary_chart.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
