name: IaC Security Check

on:
  push:
    branches:
      - test-checkov
  pull_request:

jobs:
  checkov-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install checkov

      - name: Run Checkov scan
        run: |
          checkov -d . -o json > checkov_report.json || true


      - name: Fail if critical/high issues exist
        run: |
          python .github/scripts/block_on_critical.py checkov_report.json

      - name: Convert report to Markdown
        run: |
          python .github/scripts/convert_to_md.py checkov_report.json checkov_report.md || true

      - name: Upload markdown report
        uses: actions/upload-artifact@v4
        with:
          name: checkov-markdown-report
          path: checkov_report.md

    - name: Post Checkov report as PR comment
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PR_NUMBER: ${{ github.event.pull_request.number }}
        GITHUB_REPOSITORY: ${{ github.repository }}
      run: python .github/scripts/post_pr_comment.py
